language: node_js
sudo: required
node_js:
  - 6
before_install:
  - npm install -g node-gyp
before_script:
  - npm install
  - npm install -g standard
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
